CREATE TABLE IF NOT EXISTS bina_tahsisleri (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sira_no INT NOT NULL,
    il VARCHAR(100),
    ilce VARCHAR(100),
    nereden_tahsisli ENUM('MİLLİ EMLAK', 'BELEDİYE', 'VAKIFLAR', 'MEB') NOT NULL,
    kullanim_amaci VARCHAR(255),
    mahalle_sokak_no TEXT,
    ada VARCHAR(50),
    parsel VARCHAR(50),
    pafta VARCHAR(50),
    not_aciklama VARCHAR(255),
    yapi_turu VARCHAR(100),
    kat INT,
    daire_oda VARCHAR(20),
    kullanim_durumu ENUM('aktif', 'pasif', 'bos', 'agir_hasarli', 'darul_ulum') NOT NULL DEFAULT 'aktif',
    surec_durumu ENUM('tamamlandi', 'surec_devam_ediyor') NOT NULL DEFAULT 'tamamlandi',
    tahsis_suresi_yil INT,
    bina_yasi_yil INT,
    kirasi_var_mi ENUM('evet', 'hayir'),
    kira_miktari DECIMAL(10,2),
    kira_odeniyor_mu ENUM('evet', 'hayir'),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);